name = "biashunter-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CHAT_HISTORY"
class_name = "ChatHistory"

[[migrations]]
tag = "v1"
new_classes = ["ChatHistory"]
